// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

//This file consists of different models

package model

type NewUser struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

type User struct {
	ID   int `json:"id"`
	Name string `json:"name"`
	Phone string `json:"phone"`
}

type Event struct{
	ID int `json:"id"`
	Name string `json:"name"`
	Date string `json:"date"`
	Duration string `json:"duration"`
	Location string `json:"location"`
	Category string `json:"category"`
	Description string `json:"description"`
	Price string `json:"price"`
	Hosted_by string `json:"hosted_by"`
}

type NewEvent struct{
	Name string `json:"name"`
	Date string `json:"date"`
	Duration string `json:"duration"`
	Location string `json:"location"`
	Category string `json:"category"`
	Description string `json:"description"`
	Price string `json:"price"`
	Hosted_by string `json:"hosted_by"`
}

type UpdateEvent struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Date        string `json:"date"`
	Duration    string `json:"duration"`
	Location    string `json:"location"`
	Category    string `json:"category"`
	Description string `json:"description"`
	Price       string `json:"price"`
}

type EventUser struct{
	ID int `json:"id"`
	Event_id int `json:"event_id"`
	User_id int `json:"user_id"`
}

type NewEventUser struct{
	Event_id int `json:"event_id"`
	User_id int `json:"user_id"`
}

